/* =========================================================
   ADEGAN CERITA BAB 1–2 (design/02-KANON-PROLOG-BAB1-2.md)
   Setiap adegan diputar sekali. Slot menentukan kapan dipicu:
   class (setelah salam sensei), morning (setelah menyapa teman pagi),
   dinner (makan malam), night (sebelum buku harian),
   talk:<npc> (saat bicara dengan NPC), event:<nama> (dipanggil game.js).
   ========================================================= */
import type { Scene, Line } from './types';

const ok = (jp: string, ro: string) => ({ jp, ro, ok: true });
const no = (jp: string, ro: string, why: string) => ({ jp, ro, why });

/* ---------------- PROLOG ---------------- */
export const PROLOGUE = {
  train: [
    { n: 'Musim semi. Kereta kecil melintasi sawah yang masih basah.' },
    { n: 'Di pangkuanmu ada koper bermotif batik dari Eyang, dan selembar kertas bertuliskan huruf yang belum bisa kamu baca: 「さとう はる」.' },
    { n: '"Nanti kamu akan tahu sendiri," kata Eyang waktu mengantarmu ke bandara.' },
  ] as Line[],
  station: [
    { n: '「さくらまち、さくらまち です。」 Kereta berhenti. Seorang nenek berkimono ungu melambai sambil memegang papan nama.' },
    { w: 'obaa', e: 'happy', jp: 'こんにちは。', ro: 'konnichiwa.', id: 'Halo / selamat siang.' },
    { w: 'obaa', jp: 'さとう です。', ro: 'Satou desu.', id: 'Saya Sato.' },
    { q: 'Balas sapaan Nenek!', o: [ok('こんにちは！', 'konnichiwa!'), no('さようなら！', 'sayounara!', 'さようなら itu salam perpisahan. Saat bertemu, ucapkan こんにちは.')] },
    { w: 'obaa', e: 'happy', jp: 'よく きた ね。', ro: 'yoku kita ne.', id: 'Kamu sudah datang jauh-jauh, ya.' },
    { n: 'Nenek Sato menatap koper batikmu agak lama.' },
    { w: 'obaa', e: 'sad', jp: 'その もよう… なつかしい。', ro: 'sono moyou… natsukashii.', id: 'Motif itu… membuatku rindu.' },
    { w: 'obaa', e: 'happy', t: '(membuka kamus saku) "Se-la-mat da-tang."' },
    { act: { flag: 'prolog_met_sato' } },
  ] as Line[],
  walk: [
    { n: 'Kalian berjalan pulang. Papan-papan kota tampak seperti gambar — kamu belum bisa membacanya. Tidak apa-apa, nanti pasti bisa!' },
    { n: 'Seekor kucing oranye melompat dari pagar dan menatapmu.' },
    { w: 'mochi', jp: 'にゃあ。', ro: 'nyaa.', id: 'Meong.' },
    { w: 'obaa', e: 'happy', jp: 'モチ。となり の ねこ よ。', ro: 'Mochi. tonari no neko yo.', id: 'Mochi. Kucing tetangga.' },
    { n: 'Di kejauhan, seorang kakek memanggil kucingnya. Ia melihat Nenek Sato… lalu berbalik pergi tanpa menyapa.' },
    { w: 'obaa', e: 'normal', jp: 'さあ、いきましょう。', ro: 'saa, ikimashou.', id: 'Ayo, kita jalan.' },
  ] as Line[],
  home: [
    { w: 'obaa', e: 'happy', jp: 'ここ が あなた の へや。', ro: 'koko ga anata no heya.', id: 'Ini kamarmu.' },
    { n: 'Kamar bertatami. Di dinding ada bekas paku, tempat sebuah bingkai foto dulu tergantung.' },
    { n: 'Makan malam pertama. Nenek Sato menyatukan kedua tangannya.' },
    { w: 'obaa', jp: 'いただきます。', ro: 'itadakimasu.', id: 'Selamat makan.' },
    { q: 'Tirukan Nenek sebelum makan!', o: [ok('いただきます！', 'itadakimasu!'), no('おやすみなさい！', 'oyasuminasai!', 'Itu ucapan sebelum tidur. Sebelum makan: いただきます.')] },
    { w: 'obaa', e: 'happy', jp: 'あした、がっこう。', ro: 'ashita, gakkou.', id: 'Besok sekolah.' },
    { q: 'Jawab Nenek!', o: [ok('よろしく おねがいします！', 'yoroshiku onegaishimasu!'), ok('はい！', 'hai!')] },
  ] as Line[],
  night: [
    { n: 'Malam. Bulan bersinar di jendela. Tiba-tiba terdengar suara berderit dari atas plafon.' },
    { n: 'Di ujung lorong ada tangga kecil ke loteng. Pintunya digembok. Gemboknya berkarat.' },
    { n: 'Di luar jendela, Mochi duduk di atap, memandangi bedeng bunga di taman.' },
    { n: 'Besok hari pertamamu di sekolah Jepang.' },
    { act: { flag: 'attic_seen' } },
    { act: { flag: 'prolog_done' } },
  ] as Line[],
};

/* ---------------- ADEGAN HARIAN ---------------- */
export const SCENES: Scene[] = [
  // ===== BAB 1 =====
  { id: 'c1_sensei', from: 1, until: 1, slot: 'class', cast: ['sensei'], lines: [
    { w: 'sensei', e: 'surprised', t: 'Kamu tinggal di rumah Sato-san? Wah… Sato-sensei dulu guru SD-ku!' },
    { w: 'sensei', e: 'happy', jp: 'さとう せんせい は、わたし の せんせい でした。', ro: 'Satou sensei wa, watashi no sensei deshita.', id: 'Bu Sato dulu guruku.' },
    { w: 'sensei', e: 'happy', t: 'Beliau yang membuatku suka huruf. Sekarang giliranku mengajarimu. Salam untuk beliau, ya!' },
    { act: { flag: 'sensei_knows_sato' } },
  ] },
  { id: 'c1_d2_dinner', from: 2, until: 4, slot: 'dinner', cast: ['obaa'], lines: [
    { n: 'Setelah makan, Nenek Sato membawa kertas dan pensil ke meja.' },
    { w: 'obaa', jp: 'きょう は なに を ならった の？', ro: 'kyou wa nani o naratta no?', id: 'Hari ini belajar apa?' },
    { q: 'Tunjukkan huruf yang kamu pelajari hari ini!', o: [ok('か', 'ka'), ok('き', 'ki'), ok('く', 'ku')] },
    { w: 'obaa', e: 'happy', jp: 'じょうず ね。', ro: 'jouzu ne.', id: 'Pintar, ya.' },
    { n: 'Nenek menulis 「か」 dengan indah sekali.' },
    { w: 'obaa', e: 'normal', t: 'Dulu… aku juga pernah mengajari seseorang menulis seperti ini.' },
    { w: 'obaa', e: 'happy', t: '(tertawa kecil) Ah, sudah malam. Nanti tidur, ya.' },
    { act: { flag: 'sato_hint_1' } },
  ] },
  { id: 'c1_d4_mori', from: 4, until: 10, slot: 'talk:ojii', map: 'town', cast: ['ojii'], lines: [
    { n: 'Kakek Mori sedang memancing. Mochi tidur di sebelahnya.' },
    { w: 'ojii', e: 'normal', jp: 'おまえ、さとう の いえ の こ か？', ro: 'omae, Satou no ie no ko ka?', id: 'Kamu anak yang tinggal di rumah Sato?' },
    { q: 'Jawab dengan sopan!', o: [ok('はい、そう です。', 'hai, sou desu.'), no('ちがう！', 'chigau!', 'ちがう = bukan/salah. Kamu memang tinggal di sana. Jawab: はい、そう です.')] },
    { n: 'Kakek Mori memandang tas batikmu.' },
    { w: 'ojii', e: 'sad', jp: '…インドネシア から か。', ro: '…Indoneshia kara ka.', id: '…Dari Indonesia, ya.' },
    { w: 'ojii', e: 'sad', t: '(bergumam) Sudah lama sekali…' },
    { w: 'ojii', e: 'normal', jp: 'さかな が にげる。あっち へ いけ。', ro: 'sakana ga nigeru. acchi e ike.', id: 'Ikannya kabur. Sana pergi.' },
    { n: 'Saat kamu pergi, Kakek Mori menoleh lagi ke arahmu.' },
    { act: { flag: 'mori_met' } },
  ] },
  { id: 'c1_d5_yuki', from: 5, until: 5, slot: 'morning', cast: ['yuki'], lines: [
    { n: 'Yuki berlari menyusul dari belakang. Wajahnya pucat.' },
    { w: 'yuki', e: 'sad', jp: 'テスト、こわい…', ro: 'tesuto, kowai…', id: 'Ulangannya menakutkan…' },
    { q: 'Semangati Yuki!', o: [ok('いっしょに がんばろう！', 'issho ni ganbarou!'), ok('だいじょうぶ！', 'daijoubu!'), no('しらない。', 'shiranai.', 'しらない = tidak tahu / masa bodoh. Yuki butuh semangat!')] },
    { w: 'yuki', e: 'happy', jp: 'ありがとう。きみ が いて よかった。', ro: 'arigatou. kimi ga ite yokatta.', id: 'Makasih. Untung ada kamu.' },
  ] },
  // H6: kunci (dipanggil dari mochiFound di game.js)
  { id: 'c1_key', from: 1, slot: 'event:mochi_found', cast: [], lines: [
    { n: 'Mochi sedang menggali tanah di bedeng bunga samping rumah Nenek Sato.' },
    { n: 'Lalu ia duduk bangga di samping sesuatu yang berkilau: sebuah kunci kecil berkarat, terikat pita merah yang sudah pudar.' },
    { act: { item: 'key' } },
    { act: { flag: 'key_found' } },
  ] },
  { id: 'c1_key_mori', from: 1, slot: 'event:mochi_returned', cast: ['ojii'], lines: [
    { n: 'Kakek Mori melihat tanah di kaki Mochi.' },
    { w: 'ojii', e: 'sad', jp: '…さとう の にわ に いた の か。', ro: '…Satou no niwa ni ita no ka.', id: '…Dia ada di taman Sato, ya.' },
    { w: 'ojii', e: 'happy', jp: 'ありがとう。', ro: 'arigatou.', id: 'Terima kasih.' },
    { n: 'Untuk pertama kalinya, Kakek Mori tersenyum padamu.' },
  ] },
  { id: 'c1_d7_key', from: 7, slot: 'dinner', requires: ['key_found'], cast: ['obaa'], lines: [
    { n: 'Kamu meletakkan kunci berkarat di meja makan.' },
    { w: 'obaa', e: 'surprised', jp: 'それ… どこ で？', ro: 'sore… doko de?', id: 'Itu… dari mana?' },
    { q: 'Jawab Nenek!', o: [ok('にわ です。モチ が…', 'niwa desu. Mochi ga…')] },
    { w: 'obaa', e: 'sad', jp: '…そう。', ro: '…sou.', id: '…Begitu.' },
    { w: 'obaa', e: 'normal', t: 'Itu kunci loteng. Isinya barang-barang lama… tidak penting.' },
    { w: 'obaa', e: 'normal', t: '(menatap kunci) Kalau kamu sudah bisa membaca lebih banyak hiragana… mungkin boleh kamu buka.' },
    { act: { goal: 'Pelajari 36 hiragana untuk membuka loteng' } },
    { act: { flag: 'attic_promise' } },
  ] },
  { id: 'c1_petal', from: 1, slot: 'event:letter_delivered', cast: ['obaa'], lines: [
    { n: 'Surat dari kotak pos itu ternyata untukmu — dari Eyang Dewi. Di dalamnya ada amplop kecil kedua bertuliskan huruf Jepang yang canggung: 「さとう さま」.' },
    { n: '"Cucuku, bagaimana Jepang? Tolong berikan amplop kecil ini kepada Nenek yang merawatmu. Katakan terima kasih dari Eyang."' },
    { n: 'Nenek Sato membuka amplop kecil itu. Isinya hanya satu kelopak sakura yang dikeringkan, dan tulisan 「ありがとう」.' },
    { w: 'obaa', e: 'surprised', jp: 'この じ…', ro: 'kono ji…', id: 'Tulisan ini…' },
    { w: 'obaa', e: 'sad', t: 'Terima kasih. Tolong sampaikan terima kasihku juga.' },
    { n: 'Nenek buru-buru masuk ke kamarnya.' },
    { act: { item: 'petal' } },
    { act: { flag: 'dewi_petal_sent' } },
  ] },
  { id: 'c1_d9_attic', from: 9, slot: 'night', cast: ['obaa'], cond: s => (s.kana || []).length >= 36, lines: [
    { w: 'obaa', e: 'happy', t: 'Kamu sudah belajar banyak. Ayo, kita buka bersama.' },
    { act: { card: ['やねうら', 'Loteng'] } },
    { n: 'Tangga loteng berderit. Debu beterbangan di cahaya senter: kardus, boneka hina lama, kipas… dan sebuah kotak kayu berukir bunga sakura.' },
    { n: 'Kunci berkarat diputar — klik.' },
    { n: 'Di dalamnya: setumpuk surat diikat pita, selembar halaman buku bergambar, dan foto sepia tiga remaja di pantai.' },
    { w: 'obaa', e: 'sad', jp: 'なつかしい…', ro: 'natsukashii…', id: 'Rindu sekali…' },
    { w: 'obaa', e: 'sad', t: 'Ini surat-surat dari sahabatku, 50 tahun lalu. Aku… tidak sanggup membacanya lagi.' },
    { w: 'obaa', e: 'happy', t: 'Kalau kamu mau, bacalah pelan-pelan. Tulisannya hiragana, bagus untuk latihan.' },
    { act: { item: 'sepia' } },
    { act: { flag: 'attic_opened' } },
    { act: { flag: 'letterbox_unlocked' } },
    { act: { toast: '📮 Kotak Surat terbuka! Buka dari Menu.' } },
  ] },
  { id: 'c1_d10_night', from: 10, until: 10, slot: 'night', requires: ['attic_opened'], lines: [
    { n: 'Kamu membuka surat pertama lagi. Beberapa kata masih kabur.' },
    { n: 'Hampir bisa. Tinggal beberapa huruf lagi.' },
    { w: 'mochi', jp: 'にゃ。', ro: 'nya.', id: '(Mochi mengeong dari jendela.)' },
    { act: { goal: 'Lulus ujian hiragana untuk membaca Surat #1' } },
  ] },
  { id: 'c1_d11_letter', from: 11, slot: 'night', requires: ['attic_opened'], lines: [
    { n: 'Lampu meja menyala. Surat pertama terbuka di depanmu.' },
    { act: { letter: 'L01', read: true } },
    { n: 'Tanda tangan di bawah surat ditulis dengan huruf Latin: "Dewi".' },
    { n: 'Dewi…?' },
    { n: 'Nama Eyang juga Dewi.' },
    { n: 'Kamu mengambil foto sepia. Gadis di kanan memakai kain batik… motif yang sama dengan kopermu.' },
    { act: { page: 1 } },
    { act: { stamp: ['letter1', 'Surat Pertama'] } },
    { act: { flag: 'letter1_read' } },
    { act: { flag: 'ch1_done' } },
  ] },

  // ===== BAB 2 =====
  { id: 'c2_d12_night', from: 12, slot: 'night', requires: ['attic_opened'], lines: [
    { act: { flag: 'letter2_open' } },
    { n: 'Kamu membuka surat kedua. Beberapa kata ditulis dengan huruf yang berbeda — lebih tajam dan bersudut.' },
    { n: 'Katakana! Kata-kata itu masih kabur.' },
    { act: { letter: 'L02' } },
    { act: { goal: 'Pelajari katakana untuk membaca Surat #2' } },
  ] },
  { id: 'c2_d14_call', from: 14, slot: 'night', lines: [
    { n: 'Telepon video dari Bandung! Eyang Dewi tersenyum di layar.' },
    { w: 'dewi', e: 'happy', t: 'Cucuku! Sudah bisa hiragana? Coba ucapkan salam Jepang.' },
    { q: 'Sapa Eyang dalam bahasa Jepang!', o: [ok('こんばんは！', 'konbanwa!'), no('おはよう！', 'ohayou!', 'Sekarang malam hari: こんばんは.')] },
    { w: 'dewi', e: 'happy', jp: 'じょうず ね！', ro: 'jouzu ne!', id: 'Pintar, ya!' },
    { choose: 'Tanyakan soal "Dewi" di surat itu?', opts: ['Eyang kenal Nenek Sato?', 'Tidak jadi.'] },
    { w: 'dewi', e: 'normal', t: '…Sinyalnya jelek, ya? Eyang tutup dulu. Jaga kesehatan!' },
    { n: 'Eyang menghindar. Pasti ada sesuatu.' },
    { act: { flag: 'asked_dewi_1' } },
  ] },
  { id: 'c2_d15_mai', from: 15, slot: 'talk:mai', map: 'town', cast: ['mai', 'kid'],
    spawn: { id: 'mai', x: 8, y: 17, dir: 'right', steps: ['after', 'evening'] },
    must: [{ n: 'Tok tok. Sora dan adiknya, Mai, mampir ke rumah Nenek Sato.' }],
    lines: [
      { w: 'mai', e: 'happy', jp: 'みて！たから の ちず！', ro: 'mite! takara no chizu!', id: 'Lihat! Peta harta karun!' },
      { w: 'kid', t: 'Mai menemukannya terselip di buku bergambar lama di perpustakaan. Tapi kami tidak bisa membacanya.' },
      { n: 'Kertas kuning tua, digambar tangan: Sakura-machi, pantai, gunung, kota besar, pelabuhan. Ada tanda × dengan tulisan di sebelahnya. Di pojok: tiga kelopak sakura dan inisial S・D・M.' },
      { q: 'Baca tulisan di tanda × pertama!', o: [ok('さと の いえ の うえ', 'Sato no ie no ue'), no('さと の いけ の うえ', 'Sato no ike no ue', 'Lihat lagi: い-え (rumah), bukan い-け (kolam).')] },
      { n: 'Di atas rumah Sato… loteng!' },
      { w: 'mai', e: 'happy', jp: 'あげる！', ro: 'ageru!', id: 'Buat kakak!' },
      { w: 'kid', e: 'happy', t: 'Kalau hartanya ketemu, kasih tahu kami, ya, senpai!' },
      { act: { item: 'map1976' } },
      { act: { flag: 'treasure_map' } },
      { act: { toast: '🗺️ Peta Harta 1976 masuk ke Kotak Surat.' } },
    ] },
  { id: 'c2_d16_floor', from: 16, slot: 'night', requires: ['treasure_map', 'attic_opened'], cast: ['obaa'], lines: [
    { n: 'Kamu naik ke loteng membawa peta. Tanda × itu menunjuk ke lantai dekat jendela kecil.' },
    { act: { floorGame: true } },
    { n: 'Di bawah papan yang berbunyi kosong ada bungkusan kain. Isinya selembar halaman buku bergambar… dan sebuah kamera film tua.' },
    { act: { page: 2 } },
    { act: { item: 'camera' } },
    { w: 'obaa', jp: 'なに を して いる の？', ro: 'nani o shite iru no?', id: 'Sedang apa?' },
    { n: 'Nenek Sato melihat kamera itu. Matanya berkaca-kaca.' },
    { w: 'obaa', e: 'sad', t: 'Kamera itu… milik sahabatku. Dia memotret apa saja. Katanya supaya tidak lupa.' },
    { w: 'obaa', e: 'happy', t: 'Pakailah. Kamera harus dipakai, bukan disimpan.' },
    { act: { flag: 'page2' } },
    { act: { flag: 'camera_unlocked' } },
  ] },
  { id: 'c2_d17_kenta', from: 17, slot: 'class', requires: ['page2'], cast: ['kenta'], lines: [
    { n: 'Sebelum pelajaran, Kenta melihat halaman buku bergambar yang kamu bawa.' },
    { w: 'kenta', e: 'surprised', jp: 'この え、すごい！だれ が かいた の？', ro: 'kono e, sugoi! dare ga kaita no?', id: 'Gambar ini keren! Siapa yang menggambar?' },
    { q: 'Jawab Kenta!', o: [ok('わからない。でも、ふるい よ。', 'wakaranai. demo, furui yo.')] },
    { w: 'kenta', e: 'happy', t: 'Garisnya lembut, tapi yakin. Ini gambar orang yang benar-benar suka menggambar.' },
    { w: 'kenta', e: 'happy', t: 'Kalau kamu menemukan halaman lain, tunjukkan ke aku, ya!' },
    { act: { flag: 'kenta_sees_book' } },
  ] },
  { id: 'c2_d18_cafe', from: 18, slot: 'talk:mama', map: 'kafe', cast: ['mama'], lines: [
    { n: 'Kafe itu sepi. Ibu Hana mengelap meja yang sudah bersih.' },
    { w: 'mama', e: 'happy', jp: 'いらっしゃいませ。…あら、ハナ の ともだち？', ro: 'irasshaimase. …ara, Hana no tomodachi?', id: 'Selamat datang. …Oh, teman Hana?' },
    { w: 'mama', e: 'sad', t: 'Kafe ini milik nenek Hana dulu. Sekarang… jarang ada tamu. Mungkin sebentar lagi harus tutup.' },
    { w: 'hana', e: 'sad', t: '(dari dapur) Ibu, jangan bilang begitu…' },
    { act: { flag: 'cafe_arc_seed' } },
  ] },
  { id: 'c2_d19_photo', from: 19, slot: 'talk:mama', map: 'kafe', requires: ['cafe_arc_seed'], cast: ['mama'], lines: [
    { n: 'Di dinding kafe tergantung foto hitam-putih: nenek Hana muda berdiri di depan kafe. Di meja pojok duduk tiga remaja, sedang minum soda.' },
    { n: 'Tiga remaja itu… sama dengan foto sepia di loteng!' },
    { w: 'mama', e: 'normal', t: 'Foto itu? Kata nenek Hana, mereka pelanggan setia. Selalu memesan melon soda. Salah satunya dari luar negeri.' },
    { act: { flag: 'cafe_photo_seen' } },
  ] },
  { id: 'c2_d20_ryo', from: 20, slot: 'talk:ryo', map: 'town', cast: ['ryo'], lines: [
    { n: 'Ryo memetik gitar di taman.' },
    { w: 'ryo', e: 'happy', jp: '♪ さくら の した で まってる よ…', ro: 'sakura no shita de matteru yo…', id: '♪ Aku menunggu di bawah sakura…' },
    { w: 'ryo', t: 'Aku sedang menulis lagu tentang kota ini. Tapi baru satu bait. Kata-kata berikutnya belum ketemu.' },
    { w: 'ryo', e: 'happy', t: 'Kalau kamu dengar cerita menarik soal Sakura-machi, bagi ke aku, ya.' },
    { act: { flag: 'song_v1' } },
  ] },
  { id: 'c2_d21_form', from: 21, slot: 'dinner', cast: ['obaa'], lines: [
    { n: 'Nenek Sato merapikan meja dan menemukan formulir program pertukaranmu. Di kolom "Wali di negara asal" tertulis: Dewi (nenek).' },
    { w: 'obaa', e: 'surprised', jp: '…デウィ？', ro: '…Dewi?', id: '…Dewi?' },
    { choose: 'Nenek menatapmu. Apa yang kamu katakan?', opts: ['Itu nama Eyangku.', 'Nenek kenal Dewi?'] },
    { n: 'Nenek Sato menutup mulutnya. Air matanya jatuh.' },
    { w: 'obaa', e: 'sad', t: 'Besok… setelah festival, kita bicara, ya.' },
    { act: { flag: 'sato_knows' } },
  ] },
  { id: 'c2_d22_confess', from: 22, slot: 'night', requires: ['attic_opened'], cast: ['obaa'], lines: [
    { n: 'Beranda rumah. Lampion festival masih terlihat di kejauhan. Nenek Sato membawa dua cangkir teh.' },
    { w: 'obaa', e: 'normal', t: 'Dewi adalah sahabatku. Sahabat terbaikku.' },
    { w: 'obaa', e: 'normal', t: 'Dia tinggal di kamarmu, 50 tahun lalu. Kami bertiga selalu bersama… Dewi, aku, dan…' },
    { n: 'Nenek berhenti.' },
    { w: 'obaa', e: 'sad', t: 'Setelah dia pulang ke Indonesia, dia tidak pernah membalas suratku. Mungkin… dia sudah lupa.' },
    { q: 'Apa yang kamu katakan?', o: [ok('ちがう と おもいます。', 'chigau to omoimasu.'), ok('いっしょに しらべましょう。', 'issho ni shirabemashou.')] },
    { w: 'obaa', e: 'happy', jp: 'ありがとう。', ro: 'arigatou.', id: 'Terima kasih.' },
    { act: { flag: 'letter3_open' } },
    { act: { letter: 'L03', read: true } },
    { w: 'obaa', e: 'normal', t: 'Pantai… Kami sering naik kereta ke sana. Ada kuil kecil di tebing. Tempat rahasia kami.' },
    { n: 'Tanda × kedua di peta harta kini bisa kamu baca: 「うみ の ほこら」.' },
    { act: { flag: 'letter3_read' } },
    { act: { flag: 'ch2_done' } },
    { act: { stamp: ['ch2story', 'Rahasia Nenek Sato'] } },
  ] },
];

/** Buku harian cerita (ditampilkan di buku harian malam itu bila flag-nya ada). */
export const DIARY: Array<{ flag: string; text: string }> = [
  { flag: 'ch4_done', text: 'Kakek Mori mengangguk pada Nenek di bawah kembang api. Dan Nenek akhirnya mengaku: orang ketiga itu Mori-kun.' },
  { flag: 'flashback1', text: 'Aku bermimpi menjadi Eyang di musim panas 1976. Kunang-kunang, gambar tiga kelopak… begitulah buku itu lahir.' },
  { flag: 'sato_mori_argue', text: 'Kakek Mori bilang "sudah kukirim". Tapi kenapa tangannya gemetar?' },
  { flag: 'chan_revealed', text: 'さとちゃん. Eyang dulu memanggil Nenek begitu.' },
  { flag: 'ch3_done', text: 'Kafe Hana selamat! Dan aku hampir yakin: orang ketiga di foto adalah Kakek Mori.' },
  { flag: 'page3', text: 'Nenek Sato berdiri di tempat yang sama dengan foto sepia. 50 tahun kemudian.' },
  { flag: 'market_plan', text: 'Warga akan mengadakan Pasar Pagi. Hana berani bicara di depan semua orang!' },
  { flag: 'ch2_done', text: 'Nenek Sato dan Eyang bersahabat. Tapi kenapa mereka berhenti berkirim surat? Dan siapa orang ketiga di foto itu?' },
  { flag: 'letter1_read', text: 'Aku bisa membaca semua hiragana! Dan aku membaca surat dari… Dewi. Apakah itu Eyang?' },
  { flag: 'prolog_done', text: 'Hari ini aku sampai di Sakura-machi. Aku belum bisa membaca satu huruf pun. Tapi Nenek Sato baik sekali.' },
];
