/* =========================================================
   ADEGAN CERITA BAB 4 「なつやすみ」 (design/04)
   Undangan onsen, 「さとちゃん」, ayah Kenta, kantor pos, menginap di やま
   (surat #7, jizo, KILAS BALIK #1 sebagai Dewi muda, tatami & pertengkaran),
   pohon sakura, Tanabata, foto festival 1976, Natsu Matsuri, surat #8.
   ========================================================= */
import type { Scene } from './types';

const ok = (jp: string, ro: string) => ({ jp, ro, ok: true });
const no = (jp: string, ro: string, why: string) => ({ jp, ro, why });

export const SCENES4: Scene[] = [
  { id: 'c4_d35_invite', from: 35, until: 39, slot: 'dinner', cast: ['obaa'], lines: [
    { w: 'obaa', e: 'happy', t: 'Teman kecil Nenek punya penginapan onsen di desa gunung. Dia mengundang kita menginap tiga hari!' },
    { w: 'obaa', e: 'happy', t: 'Yuki dan Hana boleh ikut. Kita berangkat hari kelima libur.' },
    { q: 'Jawab Nenek!', o: [ok('たのしみ です！', 'tanoshimi desu!'), ok('やった！', 'yatta!')] },
    { act: { flag: 'onsen_invite' } },
    { act: { flag: 'ch4_start' } },
  ] },
  { id: 'c4_d36_chan', from: 36, slot: 'night', requires: ['letter1_read'], cast: ['obaa'], lines: [
    { n: 'Kamu membuka Surat #1 lagi. Kata terakhir yang dulu kabur… kini terbaca.' },
    { act: { letter: 'L01', read: true } },
    { n: 'さとちゃん.' },
    { w: 'obaa', e: 'happy', jp: 'デウィ は、いつも「さとちゃん」って よんで くれた。', ro: 'Dewi wa, itsumo "Sato-chan" tte yonde kureta.', id: 'Dewi selalu memanggilku "Sato-chan".' },
    { w: 'obaa', e: 'sad', t: 'Nama depanku Haru. Tapi Dewi mengira "Sato" itu nama depanku, jadi dia memanggilku Sato-chan. Sudah 50 tahun tidak ada yang memanggilku begitu.' },
    { act: { flag: 'chan_revealed' } },
    { act: { stamp: ['satochan', 'さとちゃん'] } },
  ] },
  { id: 'c4_d37_kenta', from: 37, until: 39, slot: 'after', cast: ['kenta'], lines: [
    { n: 'Sepulang dari sungai, kamu melewati bengkel sepeda ayah Kenta.' },
    { n: 'Di lantai, buku sketsa Kenta tergeletak, basah oleh oli.' },
    { w: 'kenta', e: 'sad', t: '(suara ayahnya dari dalam) "Kamu tidak bisa hidup dari komik!"' },
    { w: 'kenta', e: 'sad', jp: '…わかって る よ。', ro: '…wakatte ru yo.', id: '…Aku tahu.' },
    { n: 'Setelah ayahnya masuk, Kenta memungut buku sketsanya.' },
    { q: 'Apa yang kamu katakan?', o: [ok('ケンタ の え、だいすき だよ。', 'Kenta no e, daisuki da yo.'), ok('あきらめないで。', 'akiramenaide.')] },
    { w: 'kenta', e: 'happy', t: '(tersenyum tipis) Makasih… Aku ingin ikut lomba manga di まち musim gugur nanti. Tapi aku belum berani bilang ke Ayah.' },
    { act: { flag: 'kenta_father' } },
    { act: { heart: ['kenta'] } },
  ] },
  { id: 'c4_d38_post', from: 38, until: 39, slot: 'after', cast: ['yubin'], lines: [
    { n: 'Kamu mampir ke kantor pos kota untuk membeli きって dan mengirim kartu pos ke Eyang.' },
    { q: 'Minta perangko!', o: [ok('きって を ください。', 'kitte o kudasai.'), no('きて を ください。', 'kite o kudasai.', 'Tanpa jeda っ artinya jadi "datanglah". Perangko = きって.')] },
    { n: 'Kamu menulis alamat: 「インドネシア」.' },
    { w: 'yubin', e: 'happy', t: 'Indonesia? Wah… Dulu, ada gadis Indonesia yang sering ke sini. Mengirim surat untuk ibunya setiap minggu.' },
    { w: 'yubin', t: 'Aku masih pegawai muda waktu itu. Dia selalu datang bersama seorang anak laki-laki yang membawa buku gambar.' },
    { act: { flag: 'post_hint' } },
  ] },
  { id: 'c4_d39_map', from: 39, slot: 'night', requires: ['treasure_map'], lines: [
    { n: 'Peta harta: tanda × di penginapan kini terbaca — 「おんせん の しょうじ の へや、たたみ の した」.' },
    { n: 'Kamar ber-shoji di onsen, di bawah tatami. Besok kalian berangkat ke sana!' },
    { act: { flag: 'map_spot6_read' } },
  ] },

  // ===== Menginap di onsen やま (3 sore) =====
  { id: 'c4_d40_onsen', from: 40, until: 45, slot: 'after', cast: ['okami', 'obaa', 'yuki', 'hana'], lines: [
    { act: { trip: 'onsen' } },
    { act: { card: ['やま の おんせん', 'Menginap · hari 1'] } },
    { w: 'okami', e: 'happy', jp: 'ハルちゃん！ひさしぶり！', ro: 'Haru-chan! hisashiburi!', id: 'Haru-chan! Lama tak jumpa!' },
    { n: 'Nama kecil Nenek Sato: Haru.' },
    { w: 'okami', t: 'Aturan onsen: mandi dan bilas badan dulu sebelum masuk bak. Handuk tidak boleh masuk ke air.' },
    { q: 'Sebelum masuk bak onsen, kamu harus…', o: [ok('からだ を あらう (membasuh badan)', 'karada o arau'), no('タオル を いれる (memasukkan handuk)', 'taoru o ireru', 'Handuk tidak boleh masuk ke air! Basuh badan dulu.')] },
    { w: 'okami', e: 'happy', t: 'Kamarmu… kamar yang sama dengan musim panas itu, Haru-chan.' },
    { n: 'Malam. Kamu membuka surat ketujuh di kamar penginapan.' },
    { act: { flag: 'letter7_open' } },
    { act: { letter: 'L07', read: true } },
    { n: 'Kamu, Yuki, dan Hana berbaring di futon.' },
    { w: 'hana', e: 'sad', jp: 'ずっと いっしょ って、むずかしい の かな。', ro: 'zutto issho tte, muzukashii no kana.', id: 'Selalu bersama itu… sulit, ya?' },
    { q: 'Jawab Hana!', o: [ok('でも、たいせつ だよ。', 'demo, taisetsu da yo.')] },
    { act: { heart: ['hana', 'yuki'] } },
    { act: { trip: 'home' } },
    { act: { flag: 'letter7_read' } },
    { act: { flag: 'stay_yama_1' } },
  ] },
  { id: 'c4_d41_jizo', from: 41, until: 45, slot: 'after', requires: ['stay_yama_1'], cast: ['kenta', 'nouka', 'obaa'], lines: [
    { act: { trip: 'yama' } },
    { act: { card: ['やま', 'Menginap · hari 2'] } },
    { n: 'Deretan patung jizo bertopi merah di jalan gunung. Di kotak persembahan yang paling tua…' },
    { act: { page: 5 } },
    { w: 'kenta', e: 'surprised', jp: 'おなじ ひと の え だ…', ro: 'onaji hito no e da…', id: 'Gambar orang yang sama…' },
    { w: 'nouka', e: 'happy', t: 'Pohon sakura tua di sekolahmu? Akarnya mungkin busuk karena tanahnya terlalu padat. Taburkan kompos ini dan gemburkan tanahnya.' },
    { act: { item: 'compost' } },
    { act: { flag: 'tree_advice' } },
    { n: 'Malam. Kamu melihat Nenek Sato duduk di beranda, memandangi kunang-kunang. Kamu tertidur di futon…' },
    { act: { flashback: true } },
    { act: { card: ['1976年 なつ', 'Kilas balik'] } },
    { n: 'Kamu adalah Dewi. Musim panas 1976.' },
    { w: 'sato_y', e: 'happy', jp: 'デウィ、はやく！ほたる が いる よ！', ro: 'Dewi, hayaku! hotaru ga iru yo!', id: 'Dewi, cepat! Ada kunang-kunang!' },
    { act: { game: 'fireflies' } },
    { w: 'mori_y', e: 'normal', jp: 'これ、デウィ に。', ro: 'kore, Dewi ni.', id: 'Ini, untuk Dewi.' },
    { n: 'Mori muda menyodorkan gambar: tiga kelopak sakura terbang di langit berbintang.' },
    { w: 'dewi_y', e: 'happy', jp: 'きれい！この え で、えほん を つくろう！', ro: 'kirei! kono e de, ehon o tsukurou!', id: 'Indah! Ayo buat buku bergambar dengan gambar ini!' },
    { act: { flashback: false } },
    { n: 'Kamu terbangun. Di beranda, Nenek Sato masih memandangi kunang-kunang.' },
    { act: { trip: 'home' } },
    { act: { flag: 'page5' } },
    { act: { flag: 'flashback1' } },
  ] },
  { id: 'c4_d42_tatami', from: 42, until: 45, slot: 'after', requires: ['flashback1'], cast: ['okami', 'obaa', 'ojii'], lines: [
    { act: { trip: 'onsen' } },
    { act: { card: ['やま の おんせん', 'Menginap · hari 3'] } },
    { w: 'okami', e: 'happy', t: 'Kamar lama itu? Silakan angkat tatami-nya. Pelan-pelan, ya.' },
    { n: 'Di bawah tatami ketiga ada papan dengan tanda × kecil…' },
    { act: { page: 6 } },
    { n: 'Di lobi, seorang kakek baru tiba. Kakek Mori!' },
    { w: 'obaa', e: 'surprised', jp: 'もりくん…', ro: 'Mori-kun…', id: 'Mori-kun…' },
    { w: 'ojii', e: 'normal', jp: '…さとう。', ro: '…Satou.', id: '…Sato.' },
    { n: 'Mereka bicara di taman. Kamu mendengar dari balik semak.' },
    { w: 'obaa', e: 'sad', jp: 'どうして デウィ は へんじ を くれなかった の？ あなた、てがみ を だして くれた の よね？', ro: 'doushite Dewi wa henji o kurenakatta no? anata, tegami o dashite kureta no yo ne?', id: 'Kenapa Dewi tidak membalas? Kamu sudah mengirim suratku, kan?' },
    { w: 'ojii', e: 'sad', jp: '…だした。', ro: '…dashita.', id: '…Sudah.' },
    { n: 'Kakek Mori pergi. Tangannya mengepal. Ada sesuatu yang tidak ia katakan.' },
    { act: { trip: 'home' } },
    { act: { flag: 'page6' } },
    { act: { flag: 'sato_mori_argue' } },
  ] },

  // ===== Kembali ke kota =====
  { id: 'c4_d43_tree', from: 43, until: 46, slot: 'after', cast: ['sensei', 'kenta'], lines: [
    { n: 'Pohon sakura tua di halaman belakang sekolah. Kalian menggemburkan tanah dan menaburkan kompos dari Pak Petani.' },
    { w: 'sensei', e: 'happy', t: 'Waktu kecil, Sato-sensei membawa kelas kami ke pohon ini dan bilang, "Pohon ini menyimpan janji."' },
    { n: 'Di batang pohon ada ukiran yang tertutup lumut. Belum terbaca.' },
    { act: { town: 5 } },
    { act: { flag: 'tree_care_1' } },
  ] },
  { id: 'c4_d44_tanabata', from: 44, until: 46, slot: 'after', cast: ['yuki', 'ojii'], lines: [
    { n: 'Pohon bambu di depan stasiun penuh kertas warna-warni.' },
    { act: { game: 'tanzaku' } },
    { w: 'yuki', e: 'happy', jp: 'インドネシア に いけます ように。', ro: 'Indoneshia ni ikemasu you ni.', id: 'Semoga aku bisa ke Indonesia.' },
    { n: 'Kakek Mori menggantung sebuah tanzaku, lalu buru-buru pergi. Tulisannya: 「ゆるして ください」.' },
    { n: 'ゆるして ください = maafkan aku.' },
    { act: { flag: 'mori_tanzaku' } },
  ] },
  { id: 'c4_d45_photo', from: 45, until: 46, slot: 'after', cast: ['imoya'], lines: [
    { w: 'imoya', e: 'normal', t: 'Kota ini sudah sepuluh tahun tidak mengadakan matsuri. Dulu ramai sekali. Lihat —' },
    { n: 'Foto festival tahun 1976: Sato, Dewi (yukata biru), dan Mori memegang ikan mas dalam kantong. Ketiganya tidak saling memandang.' },
    { w: 'imoya', t: 'Waktu itu mereka bertengkar, ya? Tapi besoknya sudah tertawa lagi.' },
    { act: { flag: 'festival_photo' } },
  ] },
  { id: 'c4_d45_yukata', from: 45, until: 46, slot: 'dinner', cast: ['obaa'], lines: [
    { n: 'Nenek Sato mengeluarkan yukata biru tua dari lemari dan menjahit ulang ujungnya.' },
    { w: 'obaa', e: 'happy', t: 'Ini yukata yang dulu kupinjamkan pada Dewi. Pakailah besok.' },
    { act: { item: 'yukata' } },
  ] },
  { id: 'c4_d46_matsuri', from: 46, slot: 'after', cast: ['yuki', 'hana', 'ryo', 'ojii', 'obaa'], lines: [
    { act: { card: ['なつまつり', 'Festival musim panas'] } },
    { act: { music: 'festival' } },
    { n: 'Yatai berjajar: yakisoba, takoyaki, ringo-ame, dan kolam ikan mas. Semua orang memakai yukata.' },
    { act: { game: 'taiko' } },
    { w: 'ryo', e: 'happy', jp: '♪ さくら の した で、また あおう…', ro: 'sakura no shita de, mata aou…', id: '♪ Di bawah sakura, mari bertemu lagi…' },
    { act: { flag: 'song_v2' } },
    { n: 'Kamu menemani Hana membeli ringo-ame… Saat kembali, Yuki tidak ada di tempat kalian janjian.' },
    { n: 'Seorang ibu penjual kingyo bilang: "Gadis berambut pendek tadi berjalan ke arah sungai."' },
    { w: 'yuki', e: 'sad', jp: 'わすれちゃった と おもった…', ro: 'wasurechatta to omotta…', id: 'Kukira kamu lupa…' },
    { q: 'Minta maaf!', o: [ok('ごめんね。いっしょに みよう。', 'gomen ne. issho ni miyou.'), no('ユキ が わるい！', 'Yuki ga warui!', 'Menyalahkan tidak membantu. Minta maaf dulu: ごめんね.')] },
    { act: { heart: ['yuki', 'yuki'] } },
    { n: 'ドーン！ Kembang api pertama mekar di langit. Semua teman berkumpul di jembatan.' },
    { n: 'Di ujung jembatan yang berbeda, Nenek Sato dan Kakek Mori berdiri. Lalu Kakek Mori mengangguk ke arah Nenek Sato. Pertama kalinya.' },
    { act: { town: 20 } },
    { act: { stamp: ['matsuri', 'Natsu Matsuri'] } },
    { act: { flag: 'matsuri_done' } },
  ] },
  { id: 'c4_d46_letter8', from: 46, slot: 'night', requires: ['attic_opened'], cast: ['obaa'], lines: [
    { act: { flag: 'letter8_open' } },
    { act: { letter: 'L08', read: true } },
    { w: 'obaa', e: 'happy', jp: 'そう、あの ひ も けんか した の。ばかみたい ね。', ro: 'sou, ano hi mo kenka shita no. baka mitai ne.', id: 'Ya, hari itu kami juga bertengkar. Konyol, ya.' },
    { w: 'obaa', e: 'sad', t: 'Yang ketiga di foto itu… memang Mori-kun. Kami bertiga sahabat. Tapi setelah Dewi pergi, Mori berhenti bicara padaku. Aku tidak pernah tahu kenapa.' },
    { act: { flag: 'letter8_read' } },
    { act: { flag: 'third_is_mori' } },
    { act: { flag: 'ch4_done' } },
    { act: { stamp: ['ch4story', 'Janji Musim Panas'] } },
  ] },
];

export const CLUES4 = [
  { id: 'post', flag: 'post_hint', icon: '📮', title: 'Pak Pos', text: 'Gadis Indonesia (Dewi) sering mengirim surat, ditemani anak laki-laki pembawa buku gambar.' },
  { id: 'argue', flag: 'sato_mori_argue', icon: '💢', title: 'Pertengkaran di onsen', text: '"Kamu sudah mengirim suratku, kan?" — "…Sudah." Kakek Mori menyembunyikan sesuatu.' },
  { id: 'tanzaku', flag: 'mori_tanzaku', icon: '🎋', title: 'Tanzaku Kakek Mori', text: '「ゆるして ください」 — Maafkan aku. Untuk siapa?' },
  { id: 'photo76', flag: 'festival_photo', icon: '🏮', title: 'Foto festival 1976', text: 'Trio bertengkar di festival, tapi besoknya berbaikan (Surat #8).' },
  { id: 'third', flag: 'third_is_mori', icon: '✔', title: 'Orang ketiga', text: 'Nenek Sato mengaku: orang ketiga di foto adalah Mori-kun.' },
];
